apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-booknjfkn-ingress
  annotations:
    networking.gke.io/managed-certificates: fastapi-booknjfkn-cert
    kubernetes.io/ingress.class: gce
spec:
  tls:
    - hosts:
        - booknjfkn.shop
        - www.booknjfkn.shop
  rules:
    - host: booknjfkn.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-mongo-service
                port:
                  number: 80
    - host: www.booknjfkn.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-mongo-service
                port:
                  number: 80