apiVersion: v1
kind: Secret
metadata:
  name: mongo-atlas-credentials
  namespace: default
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9zb25jaHV2YW4xMTA0X2RiX3VzZXI6U29ucGhvbmcxMjNAY2x1c3RlcjAuaHBqN281ay5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==